# Generated by Django 4.2.7 on 2025-08-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_old_national_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="criticality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
