# Generated by Django 4.2.7 on 2025-08-05 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_make_criticality_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name for the email recipient",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this email should receive notifications",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["email"],
            },
        ),
        migrations.AlterField(
            model_name="incident",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
