# Generated by Django 4.2.7 on 2025-08-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_incident_image_incidentimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="description",
            field=models.TextField(max_length=2000),
        ),
    ]
