# Generated by Django 4.2.7 on 2025-08-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_incident_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotificationEmail",
        ),
    ]
