# Generated by Django 4.2.7 on 2025-08-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_notificationemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
