# Generated by Django 4.2.7 on 2025-08-07 05:49

from django.db import migrations


def create_default_incident_types(apps, schema_editor):
    """Create default incident types for existing sites"""
    Site = apps.get_model('api', 'Site')
    IncidentType = apps.get_model('api', 'IncidentType')
    
    # Default incident types
    default_types = [
        {
            'name': 'unsafe_conditions',
            'display_name': 'Unsafe Conditions',
            'description': 'Report unsafe conditions or hazards in the workplace',
            'requires_criticality': True,
            'order': 1
        },
        {
            'name': 'unsafe_actions',
            'display_name': 'Unsafe Actions',
            'description': 'Report unsafe actions or behaviors',
            'requires_criticality': True,
            'order': 2
        },
        {
            'name': 'near_miss',
            'display_name': 'Near Miss',
            'description': 'Report near miss incidents',
            'requires_criticality': True,
            'order': 3
        },
        {
            'name': 'general_feedback',
            'display_name': 'General Feedback',
            'description': 'General feedback or suggestions',
            'requires_criticality': False,
            'order': 4
        }
    ]
    
    # Create default incident types for each existing site
    for site in Site.objects.all():
        for incident_type_data in default_types:
            IncidentType.objects.get_or_create(
                site=site,
                name=incident_type_data['name'],
                defaults={
                    'display_name': incident_type_data['display_name'],
                    'description': incident_type_data['description'],
                    'requires_criticality': incident_type_data['requires_criticality'],
                    'order': incident_type_data['order']
                }
            )


def reverse_default_incident_types(apps, schema_editor):
    """Remove all incident types"""
    IncidentType = apps.get_model('api', 'IncidentType')
    IncidentType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_incidenttype"),
    ]

    operations = [
        migrations.RunPython(create_default_incident_types, reverse_default_incident_types),
    ]
