# Generated by Django 4.2.7 on 2025-08-07 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_populate_default_incident_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="incident_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="api.incidenttype",
            ),
        ),
    ]
