# Generated by Django 4.2.7 on 2025-08-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_incident_incident_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidenttype",
            name="color",
            field=models.CharField(
                default="bg-red-500",
                help_text="Tailwind CSS color class",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="incidenttype",
            name="icon",
            field=models.CharField(
                default="AlertTriangle",
                help_text="Lucide React icon name",
                max_length=50,
            ),
        ),
    ]
